### ISSUE TITLE
x11_platform.h:39:10: fatal error: 'X11/Xcursor/Xcursor.h' file not found

### ISSUE THREAD

**Issue by aep** [PistonDevelopers/glfw-sys#11]
```
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
In file included from /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-sys-3.2.2/src/init.c:28:
In file included from /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-sys-3.2.2/src/internal.h:169:
/home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-sys-3.2.2/src/x11_platform.h:39:10: fatal error: 'X11/Xcursor/Xcursor.h' file not found
#include <X11/Xcursor/Xcursor.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
```
```
ls -lisah /usr/include/X11/Xcursor/Xcursor.h
3789131 16K -rw-r--r-- 1 root root 13K Jun  3  2014 /usr/include/X11/Xcursor/Xcursor.h

```

i'm guessing this is caused by the absurdity that cmake is. any possibility to just not use that?

**Comment by retep998** [comment]
How do you propose building glfw without cmake?

**Comment by Phi--Phi** [comment]
I found on my system that I was simply missing dependent libraries. I got this same error. Try evoking the cmake commands found in [.github/workflows/build.yml](https://github.com/PistonDevelopers/glfw-sys/blob/master/.github/workflows/build.yml). you can also see the dependent packages they need to install on Ubuntu to get this to work.

This specific issue might be solved by installing `libXcursor-devel` on your system (that's what worked for me on fedora 35).

**Comment by aep** [comment]
> This specific issue might be solved by installing libXcursor-devel on your system (that's what worked for me on fedora 35).

no. the header is right there.
closing this because it's a glfw issue.
