### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glfw-sys#20]
Currently, the version number is 3.3.5 to reflect the Glfw version.

However, this practice came from a period where Rust did not yet use semver.

We should use semver to maintain compatibility with the rest of Rust's ecosystem.

**Comment by Friz64** [comment]
If this is done, it may be helpful to put the GLFW version into the semver build metadata.

**Comment by bvssvni** [comment]
@Friz64 do you know how to add the metadata?

**Comment by Friz64** [comment]
Add it after a + in the semver version, so `0.4.1+3.3.5` (one can still use `0.4.1` to refer to this exact version).
