### ISSUE TITLE
Merge changes from glfw

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glfw-sys#3]
This is a fork of the servo/glfw, which is a fork of the original glfw repo.

There might be Servo specific changes in this repo.

Should probably update with latest changes from the original repo.

**Comment by brendanzab** [comment]
I would suggest updating to GLFW's latest stable release tag.

**Comment by bvssvni** [comment]
That would be 3.1.2 https://github.com/glfw/glfw/tree/3.1.2
