### ISSUE TITLE
Please use SPDX license name ("Zlib") in Cargo.toml

### ISSUE THREAD

**Issue by joshtriplett** [PistonDevelopers/glfw-sys#8]
The Cargo.toml file lists the license as "Zlib/Libpng". However, SPDX lists the name of the license as "Zlib"; libpng has a somewhat different license that does not match the one glfw uses. Please consider changing the `license` field in Cargo.toml to `Zlib` to match the SPDX name of the license.

I noticed this while working on an automatic packaging tool, which looks up licenses by SPDX identifier to find the corresponding license text. I checked the Cargo.toml files of every single crate on crates.io, and only this crate mentions "Zlib/Libpng"; every other crate lists this license as "Zlib".

**Comment by retep998** [comment]
Fixed.
